### ISSUE TITLE
App not working, white screen only

### ISSUE THREAD

**Issue by MohammedFadin** [MobileFirst-Platform-Developer-Center/MobileFirstBanking#1]
Hi,

When I import the project to MobileFF and deploy/run I only get a white screen. I tried on iPhone, Android emulators as well, same problem.

I'm using MobileFF 7.1

**Comment by ynunez** [comment]
@MohammedFadin Do you get any errors in the logcat or the Xcode console?

**Comment by MohammedFadin** [comment]
Nothing at all .

I'm very wondering why. Even my colleague tried as well and faced the same problem.

Fadin-IBM

**Comment by MohammedFadin** [comment]
Solved it thanks to Yoel.

You cannot view the application on the browser emulator but on the Xcode or Android simulators.
